name: CI/CD / deploy / deploy

on:
  push:
    branches: ["main"]

jobs:
  nested-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # FIX: Clean separation of python modules from native Ansible engine
      - name: Install Ansible & deps
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Install Ansible Docker Collection
        run: |
          ansible-galaxy collection install community.docker

      - name: Run playbook
        run: |
          echo "Executing nested automated deployment pipelines..."
